TOKEN="" #your token here
SUB_NAMES=("SideProject" "Vibecoding")
HISTORY=("False" "False") #remember to reset to true
CUTOFF_DATE=("11-29-2022", "03-11-2026") #The last date for experiments to be considered valid in main experiments
EXPERIMENT_DATE=("11-29-2022", "11-29-2022") #If there is historical data being considered, the last valid date for the historical experiments, if different